titie: Math + (astro/pinhole)photography
email: gwarring@gmail.com
description: > # ignore newlines until baseurl...
  Posts on mathematics, astrophotography and gerrymandering.
baseurl: ""
twitter_username: GSWarrington
github_username: GSWarrington
#
# markdown: maruku
theme: minima
exclude: ["README.md","notes.txt","Gemfile","Gemfile.lock"]
timezone: America/New_York

# analytics
google_analytics: UA-106392527-1
#
collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/